src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 255,
        minMessage: 'Le nom du cours devrait être minimun {{ limit }} characters',
        maxMessage: 'Le nom du cours ne doit pas dépasser {{ limit }} characters',
    )]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    #[Assert\PositiveOrZero]
    #[Assert\NotNull]
    private ?int $nbr_place = null;

    #[Vich\UploadableField(mapping: 'formations', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    #[Assert\Positive]
    #[Assert\NotNull]
    private ?string $price = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $UpdateAt = null;

    /**
     * @var Collection<int, Point>
     */
    #[ORM\OneToMany(targetEntity: Point::class, mappedBy: 'formation', orphanRemoval: true)]
    private Collection $points;

    /**
     * @var Collection<int, Reservation>
     */
    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'formation')]
    private Collection $reservations;

    public function __construct()
    {
        $this->points = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getNbrPlace(): ?int
    {
        return $this->nbr_place;
    }

    public function setNbrPlace(int $nbr_place): static
    {
        $this->nbr_place = $nbr_place;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->UpdateAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getPrice(): ?float
    {
        return $this->price !== null ? (float) $this->price : null;
    }
    
    public function setPrice(float $price): self
    {
        $this->price = number_format($price, 2, '.', ''); // Ensure 2 decimal places
        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(?\DateTimeImmutable $UpdateAt): static
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }

    #[ORM\PrePersist]
    public function setUpdateAtValue(): void
    {
        $this->UpdateAt = new \DateTimeImmutable();
    }

    /**
     * @return Collection<int, Point>
     */
    public function getPoints(): Collection
    {
        return $this->points;
    }

    public function addPoint(Point $point): static
    {
        if (!$this->points->contains($point)) {
            $this->points->add($point);
            $point->setFormation($this);
        }

        return $this;
    }

    public function removePoint(Point $point): static
    {
        if ($this->points->removeElement($point)) {
            // set the owning side to null (unless already changed)
            if ($point->getFormation() === $this) {
                $point->setFormation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setFormation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getFormation() === $this) {
                $reservation->setFormation(null);
            }
        }

        return $this;
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Entity\Point;
use App\Entity\Reservation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use App\Repository\PointRepository;
use App\Repository\ReservationRepository;
use App\Service\MailerService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class FormationController extends AbstractController
{
    #[Route('/formation', name: 'app_formation')]
    public function index(PaginatorInterface $paginator, FormationRepository $formationRepository, Request $request, PointRepository $pointRepository): Response
    {
        $formations = $paginator->paginate(
            $formationRepository->findAll(), /* query NOT result */
            $request->query->getInt('page', 1), /* page number */
            3 /* limit per page */
        );

        $averagePoints = [];
        foreach ($formations as $formation) {
            $averagePoints[$formation->getId()] = $pointRepository->getAveragePointForFormation($formation);
        }
    
        return $this->render('formation/index.html.twig', [
            'formations' => $formations,
            'averagePoints' => $averagePoints
        ]);
    }

    #[Route('/formation/{id}', name: 'app_formation_show', methods: ['GET'])]
    public function show(Formation $formation, PointRepository $pointRepository, PaginatorInterface $paginator, Request $request, ReservationRepository $reservationRepository): Response
    {
        $user = $this->getUser();
        $hasReservation = false;

        if ($user) {
            $existingReservation = $reservationRepository->findOneBy(['formation' => $formation, 'user' => $user]);
            if ($existingReservation) {
                $hasReservation = true;
            }
        }
        // Get comments for the given formation, ordered by ID in descending order (most recent first)
        $comments = $paginator->paginate(
            $pointRepository->findBy(
                ['formation' => $formation], // Filter by formation ID
                ['id' => 'DESC'] // Order by id in descending order (most recent first)
            ),
            $request->query->getInt('page', 1), // Page number
            3 // Limit per page
        );

        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
            'comments' => $comments,
            'hasReservation' => $hasReservation,     
        ]);
    }

    #[Route('/new/formation', name: 'app_formation_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $formation = new Formation();
        $form = $this->createForm(formationType::class, $formation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $formation = $form->getData();
                $manager->persist($formation);
                $manager->flush();
    
                $this->addFlash('success', 'Votre formation a bien été ajoutée');
                return $this->redirectToRoute('app_formation');
            } catch (\Exception $e) {
                // Log the error if needed (optional)
                // Log error: $e->getMessage()
                $this->addFlash('error', 'Erreur: la formation n\'a pas pu être ajoutée');
            }         
        }
        
        return $this->render('formation/new.html.twig', [
            'formationForm' => $form->createView()
        ]);
    }

    #[Route('/formation/edit/{id}', name: 'app_formation_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Formation $formation, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(formationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $formation = $form->getData();
                $manager->persist($formation);
                $manager->flush();
    
                $this->addFlash('success', 'Votre formation a bien été modifié');
                return $this->redirectToRoute('app_formation');
            } catch (\Exception $e) {
                // Log the error if needed (optional)
                // Log error: $e->getMessage()
                $this->addFlash('error', 'Erreur: la formation n\'a pas pu être trouvée');
            }         
        }
        
        return $this->render('formation/edit.html.twig', [
            'formationForm' => $form->createView(),
            'formation' => $formation
        ]);
    }

    #[Route('/formation/delete/{id}', name: 'app_formation_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteFormation(Formation $formation, EntityManagerInterface $manager): Response
    {
        // Check if the user has the admin role
        if (!$this->isGranted('ROLE_ADMIN')) {
            throw $this->createAccessDeniedException('Vous n\'avez pas les droits pour supprimer cette formation.');
        }
        if (!$formation) {
            return $this->json(['status' => 'error', 'message' => 'Erreur: la formation n\'a pas pu être trouvé'], 404);
        }

        try {
            $manager->remove($formation);
            $manager->flush();
            $this->addFlash('success', 'Votre formation a bien été supprimé');
            
            // Send a success response back to the frontend
            return new JsonResponse(['status' => 'success']);
        } catch (\Exception $e) {
            $this->addFlash('error', 'Erreur: la formation n\'a pas pu être supprimée');
            return new JsonResponse(['status' => 'error', 'message' => 'Erreur: ' . $e->getMessage()]);
        }
    }


    #[Route('/formation/reserve/{id}', name: 'app_formation_reserve', methods: ['GET', 'POST'])]
    public function reserve(Formation $formation, EntityManagerInterface $entityManager, ReservationRepository $reservationRepository, MailerService $mailerService): Response
    {
        $user = $this->getUser();

        // Check if the user is logged in
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        // Check if the user has already reserved a place
        $existingReservation = $reservationRepository->findOneBy(['formation' => $formation, 'user' => $user]);
        if ($existingReservation) {
            $hasReservation = true;
            $this->addFlash('error', 'Vous avez déjà réservé une place pour cette formation.');
            return $this->redirectToRoute('app_formation_show', ['id' => $formation->getId()]);
        }

        // // Check if the user has reached the maximum number of reservations (e.g., 3 reservations per user)
        // $userReservations = $reservationRepository->findBy(['user' => $user]);
        // if (count($userReservations) >= 3) { // Adjust the limit as needed
        //     $this->addFlash('error', 'Vous avez atteint le nombre maximum de réservations.');
        //     return $this->redirectToRoute('app_formation_show', ['id' => $formation->getId()]);
        // }

        // Check if the formation has available places
        $currentReservations = $reservationRepository->countByFormation($formation);
        if ($currentReservations >= $formation->getNbrPlace()) {
            $this->addFlash('error', 'Cette formation est complète.');
            return $this->redirectToRoute('app_formation_show', ['id' => $formation->getId()]);
        }

        // Create a new reservation
        $reservation = new Reservation();
        $reservation->setFormation($formation);
        $reservation->setUser($user);
        $entityManager->persist($reservation);
        $entityManager->flush();

        $mailerService->send(
            $this->getUser()->getEmail(),
            'Confirmation de votre Réservation',
            'reservation_confirm.html.twig',
            [
                'user' => $this->getUser(),
                'formation' => $formation,
            ],
        );

        $this->addFlash('success', 'Vous avez réservé une place pour cette formation avec succès.');

        return $this->redirectToRoute('app_formation_show', ['id' => $formation->getId()]);
    }

}

templates/formation/_form.html.twig
{{ form_start(formationForm, {'attr': {'novalidate': 'novalidate'}}) }} 
<div class="contact-form col-lg-12">
     <div class="col-lg-12 text-center text-light">
        {{ form_errors(formationForm) }}
    </div> 
    {{ form(formationForm) }} 
</div>
 {{ form_end(formationForm) }} 

templates/formation/edit.html.twig
{% extends 'template.html.twig' %}

{% block body %}
{% include "nav.html.twig" %}

<div class="container" id="reservation">
    <a href="{{ path('app_formation') }}" class="p-5"><i class="fa fa-arrow-left"></i> Retour</a>
    <div class="row justify-content-center mt-5">
        <div class="col-lg-8">
            <div class="col-lg-12 text-center text-light mb-5">
                <h2>Modifier des Formations</h2>
            </div>
            {% include "formation/_form.html.twig" %}
        </div>
    </div>
</div>


{% include "footer.html.twig" %}
{% endblock %}

templates/formation/index.html.twig
{% extends 'template.html.twig' %}

{% block body %}
{% include "nav.html.twig" %}
<!-- ***** Chefs Area Starts ***** -->

<section class="section" id="chefs">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 text-center">
                <div class="section-heading">
                    <h6>Nos Formations</h6>
                    <h2>Des cours que nous vous proposez</h2>
                </div>
            </div>
        </div>
        {{ include('flash.html.twig') }}

        {% if is_granted('ROLE_ADMIN') %}
        <div class="mb-3 d-flex justify-content-end">
            <a href=" {{ path('app_formation_new') }}" id="new-btn" class="main-button-icon">Créer un nouveau formation</a>
        </div>
        {% endif %}
        
        {% if formations %} 
        <div class="row">
            {% for formation in formations %}
            <div class="col-lg-4 d-flex">
                <div class="chef-item d-flex flex-column w-100">
                    <div class="thumb flex-grow-1 position-relative">
                        <div class="overlay"></div>
                        <ul class="social-icons">
                            <li><a href="{{ path('app_formation_show', { id: formation.id }) }}"><i class="fa fa-eye"></i></a></li>
                            {% if is_granted('ROLE_ADMIN') %}
                            <li><a href="{{ path('app_formation_edit', { id: formation.id }) }}"><i class="fa fa-pencil"></i></a></li>
                            <li><a href="#" data-toggle="modal" data-target="#deleteModal" 
                                data-id="{{ formation.id }}" data-name="{{ formation.name }}" data-url="{{ path('app_formation_delete', { id: formation.id }) }}" class="delete-button"><i class="fa fa-trash"></i></a></li>
                            {% endif %}
                        </ul>
                        <img src="{{ vich_uploader_asset(formation) ?: asset('assets/images/noPic.jpg') }}" alt="{{formation.name}}">
                    </div>
                    <div class="down-content mt-auto">
                        <h4>{{formation.name}}</h4>
                        <span>{{formation.date|date('d/m/Y, H:i')}}</span>
                        <br>
                        <small class="font-italic">Note Moyenne: {{averagePoints[formation.id] is not null ? averagePoints[formation.id]|number_format(2) : 'N/A'}} <i class="fa fa-star text-warning"></i></small>
                        {# pour date : formation created_at|date('d/m/Y') #}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
  
        <div class="navigation d-flex justify-content-center mt-4">
            {{ knp_pagination_render(formations) }}
        </div>
        {% else %}
        <div>Il n'y a pas de formation </div>
        {% endif %}
    </div>
</section>

<!-- Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title fs-5" id="exampleModalLabel">Confirmation de suppression</h3>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
          <span aria-hidden="true">&times;</span>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          {# <a href="#" id="confirmDeleteBtn" class="btn btn-primary" tabindex="-1" role="button">Confirmer</a> #}
          <button type="button" class="btn btn-primary confirm-delete">Confirmer</button>
        </div>
      </div>
    </div>
</div>


<!-- ***** Chefs Area Ends ***** -->
{% include "footer.html.twig" %}
{% endblock %}

templates/formation/new.html.twig
{% extends 'template.html.twig' %}

{% block body %}
{% include "nav.html.twig" %}

<div class="container" id="reservation">
    <a href="{{ path('app_formation') }}" class="p-5"><i class="fa fa-arrow-left"></i> Retour</a>
    <div class="row justify-content-center mt-5">
        <div class="col-lg-8">
            <div class="col-lg-12 text-center text-light mb-5">
                <h2>Ajouter des Formations</h2>
            </div>
            {% include "formation/_form.html.twig" %}
        </div>
    </div>
</div>


{% include "footer.html.twig" %}
{% endblock %}

templates/formation/show.html.twig
{% extends 'template.html.twig' %}

{% block body %}
{% include "nav.html.twig" %}
<section class="section" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12 d-flex flex-column justify-content-between">
                {{ include('flash.html.twig') }}
                <div class="left-text-content mb-3">
                    <div class="section-heading">
                        <h6>Nos Formations</h6>
                        <h2>{{ formation.name }}</h2>
                        <h5 class="p-1">{{formation.date|date('d/m/Y, H:i')}}</h5>
                        <h5 class="p-1">Nombres de place: {{formation.nbrPlace}}</h5>
                        <h5 class="p-1">{{ formation.price }} €</h5>
                        <div class="text-right my-3">
                        {% if app.user %}
                            {% if hasReservation is same as false %}
                                <a href="{{ path('app_formation_reserve', {'id': formation.id}) }}" class="btn btn-dark" tabindex="-1" role="button">Réserver</a>
                            {% else %}
                                <button class="btn btn-danger" disabled>Réservé</button>
                            {% endif %}
                        {% else %}
                            <a href="{{ path('app_login') }}" class="btn btn-dark" tabindex="-1" role="button">se connecter pour réserver</a>
                        {% endif %}
                        </div>
                    </div>
                    <p>{{ formation.description|raw }}</p>
                </div>
                <div class="align-self-start mt-auto">
                    <a href="{{ path('app_formation') }}" id="return-btn" class="btn btn-light" tabindex="-1" role="button"><i class="fa fa-arrow-left"></i> Retour</a>
                    {% if app.user %}
                        <a href="{{ path('app_point_new', { formation: formation.id }) }}" id="return-btn" class="btn btn-light" tabindex="-1" role="button">Laisser un commentaire</a>
                    {% else %}
                        <a href="{{ path('app_login') }}" class="text-dark" style="font-size: 14px; text-decoration: underline;">Se connecter pour laisser un commentaire</a>
                    {% endif %}
                </div>
           
            </div>
            <div class="col-lg-6 col-md-6 col-xs-12">
                <div class="right-content">
                    <div class="thumb">
                        <img src="{{ vich_uploader_asset(formation) ?: asset('assets/images/noPic.jpg') }}" alt="{{formation.name}}">
                    </div>
                </div>
            </div>
        </div>

        <h2 class="mt-5">Commentaires</h2>
        {% if comments %}
        <div class="row mt-3">
            {% for comment in comments %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card border-dark shadow-sm" style="min-height: 250px;">
                        <div class="card-header bg-dark text-light">
                            <strong>{{ comment.name }}</strong>
                            <small class="text-muted d-block">{{ comment.createdAt|date('d/m/Y H:i') }}</small>
                            {% if is_granted('ROLE_ADMIN') %}
                            <a href="#" data-toggle="modal" data-target="#deleteModal" 
                                data-id="{{ comment.id }}" data-name="{{ comment.name }}" data-url="{{ path('app_point_delete', { id: comment.id }) }}" class="delete-button float-right"><i class="fa fa-trash"></i></a>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ comment.point }} <i class="fa fa-star text-warning"></i>
                            </h5>
                            <p class="card-text">{{ comment.comment }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="navigation d-flex justify-content-center mt-4">
            {{ knp_pagination_render(comments) }}
        </div>
        {% else %}
            <p>Aucun commentaire pour le moment. Soyez le premier à en laisser un !</p>
        {% endif %}
    </div>
</section>

<!-- Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title fs-5" id="exampleModalLabel">Confirmation de suppression</h3>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
          <span aria-hidden="true">&times;</span>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          {# <a href="#" id="confirmDeleteBtn" class="btn btn-primary" tabindex="-1" role="button">Confirmer</a> #}
          <button type="button" class="btn btn-primary confirm-delete">Confirmer</button>
        </div>
      </div>
    </div>
</div>


{% include "footer.html.twig" %}
{% endblock %}